### ISSUE TITLE
Really Pretty (and a small bug report)

### ISSUE THREAD

**Issue by vsoch** [ExaWorks/exaworks.github.io#5]
Hi! I just wanted to stop by and say your site is gorgeous - the main site https://exaworks.org/ and the readthedocs (with matching branding!) It's a rare thing to see in HPC land where most sites look like they were made a decade ago. 

One possible UI bug I want to report is for the PSI/J page might have a padding issue, here is what shows up by default:

![image](https://user-images.githubusercontent.com/814322/225162698-a7f9de35-9f51-4286-a745-d498e41b1c29.png)

It looks like the style sets a padding to be page width minus 14 inches:

![image](https://user-images.githubusercontent.com/814322/225162756-a5316f3d-70e3-4722-ae6a-dae65f48ac13.png)

I'm not sure the rationale for the above, but even setting it to 50px looked good for me on mobile and web:

![image](https://user-images.githubusercontent.com/814322/225162965-a7b75de2-7e46-4c6d-bd40-9bd7bbe82c7b.png)
![image](https://user-images.githubusercontent.com/814322/225162997-923c2764-ccbd-4e6c-aa37-ac1997bdcb16.png)

**Comment by hategan** [comment]
Thank you for the nice words.

The rationale is that we want to restrict the main content width and somewhat center it if necessary. That part really shouldn't kick in unless the display is wider than 14in, and, even so, it should not cause the text to be narrower than 14in, which it seems to be doing in your case.

That said, it clearly looks off in your screenshot. Would you mind sharing your display resolution and the DPI if you happen to know it?

In the mean time, I'll try to think of an alternative solution to having the margin set to a sensible value so that the content is still somewhat centered on high resolution displays.

**Comment by vsoch** [comment]
> That said, it clearly looks off in your screenshot. Would you mind sharing your display resolution and the DPI if you happen to know it?

I have a an external monitor, 27 inches, maximum resolution 2560 x 1440

**Comment by hategan** [comment]
FYI: https://github.com/ExaWorks/psij-python/pull/361

**Comment by hategan** [comment]
Fix has been merged.

**Comment by vsoch** [comment]
Looks good - thank you! 
![image](https://user-images.githubusercontent.com/814322/226752959-a630b1b3-7c31-4fa1-932c-ed1b7b10e8fd.png)
